version: "3.7"

services:
  # Servis adlarını tanımlıyoruz.
  flask:
    # Build alacağı Dockerfile bulunan directory'i belirtiyoruz.
    build: ./flask
    # Container adını belirtiyoruz
    container_name: getir_flask
    # Servisin herzaman restart olmasını belirtiyoruz
    restart: always
    # container içindeki environment variable değerlerinde değişiklik yapıyoruz.
    environment:
      - APP_NAME= GetirApp
    # Any ports listed using `expose` will only be accessible to internal services/containers
    expose:
      - 5000
    ports:
      - 5000:5000
    command: python app.py 
  
  geoserver:
    ##platform: linux/arm64/v8 ## macbook m1 chip icin  belirtilmesi gerekiyor.
    # Build alacağı Dockerfile bulunan directory'i belirtiyoruz.
    build: ./geoserver
    # Container adını belirtiyoruz
    container_name: getir_geoserver
    # Servisin herzaman restart olmasını belirtiyoruz
    restart: always
    # container verilerinin tutulduğu volume belirtiliyor
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    expose:
      - 8090
    ports:
      - "8090:8080"
    # container içindeki environment variable değerlerinde değişiklik yapıyoruz.
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin  
    links:
      - postgis

  postgis:
    hostname: postgis
    build: ./postgis 
    container_name: getir_db
    restart: on-failure
    expose:
      - 11117
    ports:
      - 11117:5432
    volumes:
      - postgres_data_g:/var/lib/postgresql/data2/
    environment: 
      POSTGRES_USER: postgres #docker 
      POSTGRES_DB: postgres #template_postgis
      POSTGRES_PASSWORD: docker
      ALLOW_IP_RANGE: '0.0.0.0/0'
      POSTGRES_DBNAME: getirdb

volumes:
  geoserver-data:
    external: true
  postgres_data_g:
    external: true
